# Generated by Django 4.1 on 2022-08-21 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0002_alter_user_is_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='location_longtitude',
            new_name='location_longitude',
        ),
    ]
